# Generated by Django 4.2.7 on 2023-11-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0002_userprofile_display_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_picture',
        ),
    ]
